-- gotPuzzled database schema
-- Generated by Sequelize sync. Run syncAndSeed.js to apply.

CREATE DATABASE IF NOT EXISTS gotpuzzled;
USE gotpuzzled;

CREATE TABLE IF NOT EXISTS users (
    userId      INT AUTO_INCREMENT PRIMARY KEY,
    firstName   VARCHAR(255) NOT NULL,
    lastName    VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    userRole    ENUM('player','admin','manager') DEFAULT 'player',
    theme       VARCHAR(255) DEFAULT 'light',
    createDate  DATETIME,
    updateDate  DATETIME
);

CREATE TABLE IF NOT EXISTS admin_profiles (
    adminId     INT AUTO_INCREMENT PRIMARY KEY,
    userId      INT NOT NULL,
    accessLevel ENUM('admin','manager') NOT NULL,
    FOREIGN KEY (userId) REFERENCES users(userId) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS scores (
    scoreId   INT AUTO_INCREMENT PRIMARY KEY,
    userId    INT  NOT NULL,
    puzzleId  INT  NULL,
    pieces    INT  NOT NULL,
    rounds    INT  NOT NULL,
    timeScore VARCHAR(8) NOT NULL,
    FOREIGN KEY (userId)   REFERENCES users(userId)     ON DELETE CASCADE
);
